### PR TITLE
modified environment.yml for metapackage 2020.03.30

### PR DESCRIPTION
**Pull request by scottyhq**
First test of chatops following up on https://github.com/pangeo-data/pangeo-stacks-dev/pull/33

### CODE REVIEW

**Comment by tjcrone** [comment]
I mean, getting a rocket is nice.

**Comment by scottyhq** [comment]
/condalock

Rockets are pretty great. Failed first launch though. trying again

**Comment by scottyhq** [comment]
/condalock

and again

**Comment by scottyhq** [comment]
Cool. that worked, but workflow didn't retrigger due to actions access token, trying one more time with repo-scoped access token.

**Comment by scottyhq** [comment]
chatops workflow fails workflow fails at push step if nothing new to commit:
https://github.com/pangeo-data/pangeo-stacks-dev/actions/runs/67860171 
```
nothing to commit, working tree clean
13
##[error]Process completed with exit code 1.
```

**Comment by scottyhq** [comment]
closing since this was just a CI test

**Pull request closed without merging**
