### PR TITLE
force rebuild to get latest panel 

### PR DESCRIPTION
**Pull request by rsignell-usgs**
/condalock

Really just kicking a new build to get latest "panel" 0.9.5 build 1 on conda-forge.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@scottyhq can we do that slash-command-dispatch from an issue?

**Comment by scottyhq** [comment]
Right now we are only setup to run in PRs https://github.com/pangeo-data/pangeo-stacks-dev/blob/e5c550f971ec4064831f7afd8120e13801283186/.github/workflows/ChatOps.yml#L15 .

But that could be a neat ability. Probably would enable a separate command only for administrators such as `/rebuild-all` that could be run from issues. The CI is definitely still a work in progress

**Comment by scottyhq** [comment]
Looks like the build didn't work:
```
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/glib-2.58.3-py37he00f558_1004.tar.bz2>
1647
Elapsed: 00:00.195006
1648
CF-RAY: 58053a105d85eaa2-IAD
1649

1650
An HTTP error occurred when trying to retrieve this URL.
1651
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

Despite the message about intermittent failures I ran into this same thing yesterday, so might be an issue with conda / conda-lock

**Comment by ocefpaf** [comment]
That file was moved to broken: https://anaconda.org/conda-forge/glib/files

We need to find a better way to report that. However, the new solve should not find that file :-/

**Comment by scottyhq** [comment]
/condalock

It just built for me locally, so re-triggering build.

**Comment by rabernat** [comment]
I am fascinated by what is happening here and want to understand it better.

What does `/condalock` do?

**Pull request merged**
